name: "Test CI "
on:
  pull_request:
  workflow_dispatch:

jobs:
  detect-changes:
    name: "Detect changes"
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.templates.outputs.templates }}
      features: ${{ steps.templates.outputs.features }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "find all templates"
        id: templates
        run: ./build.sh ListTemplates -GithubOutput "$GITHUB_OUTPUT"
  test-templates:
    needs: [detect-changes]
    name: "Hey there: ${{ matrix.template }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        template: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run test for '${{ matrix.template }}'
        id: smoke_test
        run: echo 'Hi man'
  test-features:
    needs: [detect-changes]
    name: "Hey there: ${{ matrix.feature }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        feature: ${{ fromJSON(needs.detect-changes.outputs.features) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run test for '${{ matrix.feature }}'
        id: smoke_test
        run: echo 'Hi man'
