name: "CI - Test Templates"
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        templates: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run test for '${{ matrix.templates }}'
        id: smoke_test
        run: echo 'Hello'
