name: "Test Template & Features"
on:
  pull_request:
  workflow_dispatch:

jobs:
  changes:
    name: Detect changed features & templates
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.templates.outputs.templates }}
      features: ${{ steps.templates.outputs.features }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout-cone-mode: false
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: "git log"
        run: git log --oneline -n 10
      - name: "git branch"
        run: git branch
      - name: "git diff"
        run: git status
      - name: find changed templates & features
        id: templates
        run: ./build.sh ListTemplatesAndFeatures -GithubOutput "$GITHUB_OUTPUT"

  test-templates:
    if: ${{ needs.changes.outputs.templates }}
    needs: [changes]
    name: "Test template: ${{ matrix.template }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        template: ${{ fromJSON(needs.changes.outputs.templates) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install dev containers
        run: npm install -g @devcontainers/cli
      - name: Run test for '${{ matrix.template }}'
        id: smoke_test
        run: echo 'Hi man'

  test-features:
    if: ${{ needs.changes.outputs.features }}
    needs: [changes]
    name: "Test feature: ${{ matrix.feature }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        feature: ${{ fromJSON(needs.changes.outputs.features) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install dev containers
        run: npm install -g @devcontainers/cli
      - name: Run test for '${{ matrix.feature }}'
        id: smoke_test
        run: ./build.sh TestFeature -Feature '${{ matrix.feature }}'
