name: "Release"
on:
  workflow_dispatch:

jobs:
  changes:
    name: features
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.changed_files.outputs.templates }}
      features: ${{ steps.changed_files.outputs.features }}
      changesToNuke: ${{ steps.changed_files.outputs.changesToNuke }}
    steps:
      - name: find changed templates & features
        id: changed_files
        run: ls -la
