name: "Update Version"
on:
  workflow_dispatch:

jobs:
  changes:
    name: features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: pull branch
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: "Cache: .nuke/temp, ~/.nuget/packages"
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: run update features
        run: |
          for feature in features/src/*; do
            ./build.sh ReleaseFeature -Feature ${feature##*/};
          done
