name: "Release"
on:
  workflow_dispatch:

jobs:
  changes:
    name: features
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.changed_files.outputs.templates }}
      features: ${{ steps.changed_files.outputs.features }}
      changesToNuke: ${{ steps.changed_files.outputs.changesToNuke }}
    steps:
      - uses: actions/checkout@v3
        name: pull branch
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: find changed templates & features
        id: changed_files
        run: git branch
